name:                irc-bot
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/AdituV/irc-learning/irc-bot#readme
license:             BSD3
author:              Iris Ward
maintainer:          aditu.venyhandottir@gmail.com
copyright:           2018 Iris Ward
category:            Network
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs:      src
